
# ── tmux snippet ────────────────────────────────────────────────────────────
# fmux does not edit the user's ~/.tmux.conf. It owns exactly one file of its own, and borrows only
# a single `source-file` line in the user's config. Delete it and every trace disappears — the same
# philosophy as a PATH shim.
# (If we spliced our block into someone else's config file, removing it would require us to edit
#  their file. If that edit ever goes wrong even once, the user's tmux fails to start — a risk we
#  refuse to carry at all.)
FMUX_TMUX_CONF="$FMUX_CONF_DIR/tmux.conf"

# Print the list of no-prefix keys to unbind to stdout (space-separated, deduplicated).
# tmux doesn't have a "vanishes on its own once it's not in the config" model — once a key is
# bound, it stays until the server dies. So removing a key from the config isn't enough; without
# also issuing an unbind, the removed key keeps working.
#
# There are exactly two sources — both are "keys fmux actually bound":
#   ① the key we're about to bind now (makes reapplication idempotent)  ② `bind -n` lines still
#   present in the previous snippet.
# There used to be a third source here: a static candidate list (C-Left M-Left M-b C-Right M-Right
# M-f). That unbound those six keys even under the default (safe) preset — where we hadn't bound a
# single key of our own — meaning **we deleted bindings someone else had set up**. That flatly
# contradicted the README's "steals no key until you say so" and was never disclosed to the user
# (team release gate B3). A key we never bound isn't ours to touch — thanks to source ②, any key we
# did bind dies on its own, whatever its name turns out to be.
fmux_tmux_conf_unbind_list() {
    local seen=' ' k line fast
    fast=$(fmux_conf_get key_summon_fast)
    for k in $fast; do
        case "$seen" in *" $k "*) continue ;; esac
        fmux_conf_is_tmux_key "$k" || continue
        seen="$seen$k "
    done
    if [ -r "$FMUX_TMUX_CONF" ]; then
        while IFS= read -r line || [ -n "$line" ]; do
            case "$line" in 'bind -n '*) ;; *) continue ;; esac
            line=${line#bind -n }
            k=${line%% *}
            case "$seen" in *" $k "*) continue ;; esac
            fmux_conf_is_tmux_key "$k" || continue
            seen="$seen$k "
        done < "$FMUX_TMUX_CONF"
    fi
    printf '%s' "${seen# }"
}

# Print the snippet's contents to stdout. The file itself is untouched — so `fmux --tmux-conf` lets you look before you leap.
fmux_tmux_conf_render() {
    # The popup summon command. SELFQ is a quoted form that survives even if the path has spaces
    # (00-header.sh). --from '#S' tells it the current session — so it can exclude itself from the list (90-main.sh:251).
    # Title on the popup border. The project is fmux; tt is only the short alias you type, so the
    # frame says the name of the thing. ⌘ marks it as a command surface at a glance.
    # The border is drawn in the accent colour, the same one the list and the help screen use.
    #   Without -S tmux paints the border in its own default, so a popup bound here and a popup
    #   bound by hand elsewhere look like two different tools (measured — the author had both).
    local _acc; _acc=$(fmux_conf_num accent 255)
    local popup="display-popup -E -w 85% -h 75% -b rounded -S 'fg=colour$_acc' -T ' ⌘ fmux ' $SELFQ --from '#S'"
    local k fast

    printf '# File generated by fleetmux — do not hand-edit. fmux config set … rewrites it.\n'
    printf '# Add only this one line to your own config (~/.tmux.conf):\n'
    printf '#   source-file %s\n' "$FMUX_TMUX_CONF"
    printf '\n'

    # Unbinding comes first. Even the key we're about to bind now must be walked through and
    # rebound for reapplication to be idempotent.
    # unbinding a key that isn't actually bound makes tmux error, but -q swallows it — there's no
    # reason to show the user ten lines of "unknown key" on the first source.
    for k in $(fmux_tmux_conf_unbind_list); do
        printf 'unbind -n -q %s\n' "$k"
    done
    printf '\n'

    # The summon key that comes after prefix. Skipped if empty — some people want no-prefix keys only.
    k=$(fmux_conf_get key_summon)
    if [ -n "$k" ]; then
        # The parser (05-config.sh) already filters the value's character set, but a hand-edited
        # file can reach this point too, so the renderer checks the tmux key shape once more. If it
        # doesn't pass, only that line is quietly dropped, with a notice — making the whole snippet
        # unusable would mean a single summon-key typo wipes out the entire cockpit.
        if fmux_conf_is_tmux_key "$k"; then
            printf 'bind %s %s\n' "$k" "$popup"
        else
            printf 'fleetmux: key_summon is not a tmux key name — skipping: %s\n' "$k" >&2
        fi
    fi

    # The list of no-prefix summon keys. The same physical key arrives under different names on
    # different terminals, so we bind all of them.
    fast=$(fmux_conf_get key_summon_fast)
    for k in $fast; do
        if fmux_conf_is_tmux_key "$k"; then
            printf 'bind -n %s %s\n' "$k" "$popup"
        else
            printf 'fleetmux: %s in key_summon_fast is not a tmux key name — skipping\n' "$k" >&2
        fi
    done

    if fmux_conf_on status_badges; then
        printf '\n# Fleet badges in the status bar — ⏸ waiting · ✓ finished · ✻ working.\n'
        printf '#   Knowing who is stuck without opening anything is the point of the tool, so this\n'
        printf '#   is on by default. Turn it off with: fmux config set status_badges off\n'
        # ⛔ Never append unconditionally. This file is re-sourced on every config reload, and a
        #    config that does not set status-right itself (the tmux default) keeps whatever was
        #    there — so `set -ag` would stack another copy of the badges on every reload.
        # ⛔ And never "save the original" into a user option either. Options are stored, not
        #    expanded, so `set -g @base '#{status-right}'` saves the literal text #{status-right},
        #    a self-reference. Expanding it instead (set -F) is worse: a status-right holding
        #    %H:%M or #{session_name} would be frozen to the values it had at that instant.
        # So: append only when our fragment is not already in there. The test is a no-op
        # substitution — if removing the marker changes nothing, it was never there.
        printf "run-shell \"'%s' --status-bind\"\n" "$SELF"
        # Badges are only as fresh as the redraw interval. 5s is the cadence the hooks assume.
        printf 'set -g status-interval 5\n'
        # tmux truncates status-right at status-right-length, and the default is 40 — enough for a
        # clock and little else. Measured 2026-08-06: on a stock macOS setup the badges were being
        # appended correctly and then cut off unseen, which reads exactly like "it does not work".
        # A single ⏸ with a session name is 20 characters on its own.
        # The raise happens in fmux, not here: `#{status-right-length}` is not available as a
        # format, so `if -F` cannot compare it (measured — the guard silently never fired). And it
        # must be a raise, never a set: someone who already widened it keeps their value.
        printf "run-shell \"'%s' --status-fit\"\n" "$SELF"
    else
        # Off means off, including on a server where it is already drawn. `tmux show -gv` hands
        # back the **unexpanded** format string, so cutting our fragment out of it and writing it
        # back leaves the rest of the line exactly as it was, formats and all.
        printf '\n# status_badges=off — take our fragment back out, leave the rest of the line alone.\n'
        printf "run-shell \"'%s' --status-unbind\"\n" "$SELF"
    fi

    if fmux_conf_on snapshot_on_exit; then
        printf '\n# Record once more on the way out — so the manifest never misses the final moment.\n'
        # client-detached is -b. If the snapshot held onto whoever's leaving, detach would visibly lag.
        printf "set-hook -g client-detached 'run-shell -b \"%s --snapshot >/dev/null 2>&1\"'\n" "$SELF"
        # session-closed must be synchronous. When the last session closes the server is going
        # down, so a process launched in the background disappears along with its parent before it
        # gets to run (measured in practice).
        printf "set-hook -g session-closed 'run-shell \"%s --snapshot >/dev/null 2>&1\"'\n" "$SELF"
    fi
}

# Is the user's config actually sourcing this snippet — the only basis for whether it's okay to
# apply changes to the live tmux server. "We write our file" and "we apply it to someone else's
# server" are two different consents (team release gate B4).
#   The judgment rule must match install.sh's already_sourced: **anchored to line start + exact
#   argument match**. A partial match would treat even a comment line, or a broken line concatenated
#   without a newline ("set -g mouse onsource-file …"), as "linked". The candidate files are the
#   same two as install.sh's pick_tmux_conf.
#   A tilde (~/…) is expanded before comparing (team release gate I1): tmux handles `source-file
#   ~/.config/…` normally and the README teaches that exact form, but comparing only exact absolute
#   paths would read that person's config as "not linked" — then fmux config set wouldn't apply to the
#   live server while the screen still prints success, and re-running the installer appends yet
#   another duplicate source line. **A hole that catches exactly the person who followed the docs to the letter.**
fmux_tmux_conf_linked() {
    local f line rest
    for f in "$HOME/.tmux.conf" "${XDG_CONFIG_HOME:-$HOME/.config}/tmux/tmux.conf"; do
        [ -r "$f" ] || continue
        while IFS= read -r line || [ -n "$line" ]; do
            while :; do case "$line" in [[:blank:]]*) line=${line#?} ;; *) break ;; esac; done
            case "$line" in
                'source-file '*) rest=${line#source-file } ;;
                'source '*)      rest=${line#source } ;;
                *) continue ;;
            esac
            # Strip the leading flag (-q etc), strip trailing whitespace/quotes, then compare exactly.
            # Word splitting ($rest walked with for) is not used — in a shell with globbing on, a *
            # in someone else's config line would expand to a filename.
            while :; do case "$rest" in '-'*' '*) rest=${rest#* } ;; *) break ;; esac; done
            while :; do case "$rest" in *[[:blank:]]) rest=${rest%?} ;; *) break ;; esac; done
            case "$rest" in '"'*'"'|"'"*"'") rest=${rest#?}; rest=${rest%?} ;; esac
            # Expand the tilde. Why the pattern is quoted as \~: bash also applies tilde expansion
            # to the word in ${var#word}, so without quoting it, the pattern would expand to $HOME first and fail to match.
            case "$rest" in
                '~')   rest="$HOME" ;;
                '~/'*) rest="$HOME/${rest#\~/}" ;;
            esac
            [ "$rest" = "$FMUX_TMUX_CONF" ] && return 0
        done < "$f"
    done
    return 1
}

# Write the snippet atomically. If the user has wired this file into their own config and we're inside tmux right now, apply it immediately.
fmux_tmux_conf_write() {
    local tmp
    mkdir -p "$FMUX_CONF_DIR" 2>/dev/null || true
    tmp="$FMUX_TMUX_CONF.tmp.$$"
    # The render reads the previous snippet (to collect unbinds) — so we must write to tmp fully
    # before mv'ing it into place. Redirecting straight to the original would truncate it mid-read.
    # stderr is not suppressed here — if the hand-edited config has a strange key, the person
    # writing it needs to know. The call site that must stay quiet (fmux_conf_resnip) wraps itself with 2>/dev/null.
    fmux_tmux_conf_render > "$tmp" || { rm -f "$tmp"; return 1; }
    mv -f "$tmp" "$FMUX_TMUX_CONF" || { rm -f "$tmp"; return 1; }
    # Applying to the live server only happens when both are true:
    #   ① we're inside tmux right now  ② the user's config actually has a line sourcing this file
    # Skipping ② would push our bindings even into the server of someone "not yet linked" — just
    # running `fmux --tmux-conf --write` to eyeball the snippet would change their keys as a side effect.
    # For someone not linked, nothing happens either at the next tmux start or on this server (only our file is up to date).
    if [ -n "${TMUX:-}" ] && fmux_tmux_conf_linked; then
        tmux source-file "$FMUX_TMUX_CONF" 2>/dev/null || true
    fi
    return 0
}

# Take our badge fragment back out of status-right.
#
# This lives here, in bash, rather than inline in the snippet. The snippet is tmux config, and a
# run-shell body has to survive tmux quoting **and** shell quoting at once — the first attempt died
# with "too many arguments" before running at all. The snippet now calls one command with one
# argument, which is the same rule that got the ? binding fixed: anything needing a shell runs in
# this file, which has a shebang we chose.
#
# `tmux show -gv` hands back the **unexpanded** format string, so whatever else is on that line —
# %H:%M, #{session_name} — is written back exactly as it was, still live.
# Make room for the badges. tmux cuts status-right at status-right-length, default 40 — a clock
# and a date already fill that, so appended badges are drawn and then truncated away unseen.
# Raise only: a config that already allows more keeps its own value.
# Put the badges at the **front** of status-right.
#
# They went on the end at first, and that was wrong twice over: the most urgent signal in the tool
# sat behind the clock and the date, and when the line ran out of width the badges were the first
# thing cut (measured — status-right-length defaults to 40).
#
# Prepending has no tmux flag the way `set -ag` appends, so it happens here: read the current line,
# and only if our fragment is not already in it, write it back with ours in front. Reading with
# `tmux show -gv` returns the **unexpanded** format string, so everything else on that line —
# %H:%M, #{pane_title} — is written back exactly as it was and stays live.
if [ "${1:-}" = "--status-bind" ]; then
    # Strip any fragment of ours from **both** halves first, then put one back at the very front
    # of status-right — the leftmost slot of the right-hand group, ahead of the clock and the
    # date, without pushing the window list around. In that order this is idempotent (re-sourcing
    # cannot stack copies) and a migration at once: an install that had them elsewhere gets moved.
    for _o in status-left status-right; do
        _cur=$(tmux show -gv "$_o" 2>/dev/null) || continue
        _new=$(printf '%s' "$_cur" | sed 's| *#([^)]*--status)||g')
        [ "$_cur" = "$_new" ] || tmux set -g "$_o" "$_new" 2>/dev/null || true
    done
    cur=$(tmux show -gv status-right 2>/dev/null) || exit 0
    tmux set -g status-right "#($SELF --status)$cur" 2>/dev/null || true
    exit 0
fi

if [ "${1:-}" = "--status-fit" ]; then
    # status-left-length defaults to **10** — that does not fit a single badge with a session name,
    # so without this the badges are drawn and then cut off, which looks exactly like not working.
    for _o in status-left-length status-right-length; do
        cur=$(tmux show -gv "$_o" 2>/dev/null) || continue
        case "$cur" in ''|*[!0-9]*) cur=0 ;; esac
        [ "$cur" -ge 120 ] || tmux set -g "$_o" 120 2>/dev/null || true
    done
    exit 0
fi

if [ "${1:-}" = "--status-unbind" ]; then
    for _o in status-left status-right; do
        cur=$(tmux show -gv "$_o" 2>/dev/null) || continue
        new=$(printf '%s' "$cur" | sed 's| *#([^)]*--status)||g')
        [ "$new" = "$cur" ] || tmux set -g "$_o" "$new" 2>/dev/null || true
    done
    exit 0
fi

if [ "${1:-}" = "--tmux-conf" ]; then
    # Contract (05-config.sh:53): the render below calls fmux_conf_get repeatedly via $(...) — all
    # subshells, so unless fmux_conf_load is fired here first as a bare statement, one broken config
    # line repeats the same warning once per key looked up.
    fmux_conf_load
    if [ "${2:-}" = "--write" ]; then
        fmux_tmux_conf_write || { echo "cannot write snippet: $FMUX_TMUX_CONF" >&2; exit 1; }
        printf '%s\n' "$FMUX_TMUX_CONF"
    else
        fmux_tmux_conf_render
    fi
    exit 0
fi
